# Generated by Django 3.2.25 on 2024-10-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured_image',
        ),
    ]
